PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX chebi: <http://purl.obolibrary.org/obo/chebi/>
PREFIX chebidb: <http://purl.obolibrary.org/obo/CHEBI_>
PREFIX chebirel: <http://purl.obolibrary.org/obo/CHEBI#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX bp3: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX reactome: <http://www.reactome.org/biopax/40/48887#>
PREFIX abstraction:<http://abstraction/#>

SELECT DISTINCT ?pathwayID ?subPathwayID
WHERE {
  ?pathway rdf:type bp3:Pathway .
  ?pathway bp3:pathwayComponent ?subPathway .
  ?subPathway rdf:type bp3:Pathway .

  ?pathway bp3:xref ?pathwayXref .
  ?pathwayXref rdf:type bp3:UnificationXref .
  ?pathwayXref bp3:db "Reactome" .
  ?pathwayXref bp3:id ?pathwayID .
  
  ?subPathway bp3:xref ?subPathwayXref .
  ?subPathwayXref rdf:type bp3:UnificationXref .
  ?subPathwayXref bp3:db "Reactome" .
  ?subPathwayXref bp3:id ?subPathwayID .
}