PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX chebi: <http://purl.obolibrary.org/obo/chebi/>
PREFIX chebidb: <http://purl.obolibrary.org/obo/CHEBI_>
PREFIX chebirel: <http://purl.obolibrary.org/obo/CHEBI#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX bp3: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX reactome: <http://www.reactome.org/biopax/40/48887#>
PREFIX abstraction:<http://abstraction/#>

CONSTRUCT {
  ?pathway abstraction:NextStepPathway ?nextPathway
}
WHERE {
  ?pathway rdf:type bp3:Pathway .
  ?nextPathway rdf:type bp3:Pathway .
  
  ?pathway bp3:pathwayOrder ?pathwayStep .
  ?nextPathway bp3:pathwayOrder ?nextStep .
  
  ?pathwayStep bp3:nextStep ?nextStep .
  
  FILTER (?pathway != ?nextPathway)
}